spring:
  application:
    name: swapi-reports
  datasource:
    url: jdbc:h2:mem:swapi-reports
    driver-class-name: org.h2.Driver
    username: sa
    data-password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: false
    properties.hibernate.hbm2ddl.auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase/changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true

swapi:
  client:
    base-url: "https://swapi.co"
    people-uri: "/api/people/"
    films-uri: "/api/films/"
    planets-uri: "/api/planets/"

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
