spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ask
    password: ask123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties.hibernate.show_sql: false
    properties.hibernate.hbm2ddl.auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase/changelog-master.xml
    enabled: true
    user: ask
    password: ask123
    url: jdbc:postgresql://192.168.99.100:5432/postgres
  h2:
    console:
      enabled: true